### ISSUE TITLE
Embedding unknown GH sequences into characterized sequences analysis

### ISSUE THREAD

**Issue by sivankij** [DallasThomas/SACCHARIS#10]
Hi there,
Thank you for SACCHARIS!

I've managed to install all dependencies and get the tool running, and now I want to analyze a GH33 sequence that is not yet characterized, derived from an isolate I've sequenced. In the SACCHARIS paper this is exactly what you did with GH43- embedded an unknown enzyme sequence into the Saccharis analysis of all characterized sequences. 
I wanted to ask how you performed the embedding and at what step of the process did you incorporate the unknown sequence.

Thanks!
Sivan

**Comment by DallasThomas** [comment]
Hello Sivan,

To embed other sequences within your run you would include a separate sequence file with those sequences and use the -s <filename> flag when you run Saccharis.  Within the man/help page for Saccharis, using either -h or man -- it will give you the following information

 --seqfile | -s    </path/filename>

     : If you would like to add your own sequences to this run - this is your 
       chance.  Sequences MUST be in FASTA FORMAT - if they are not the script
       will fail.  Make sure to include path with filename.
     : Sequence Header lines must start with a uniqure 9 character string with
       the following format:

       -> >U[0-9]{1,8} - That is a >U followed by 8 digits

	ex. U00000001

I hope this helps.  

Dallas

**Comment by sivankij** [comment]
Thank you for the quick response!

Sivan

**Comment by DallasThomas** [comment]
No problem.  Hope things work well for you.  Have a great day.

Dallas
