### ISSUE TITLE
Appending Step error

### ISSUE THREAD

**Issue by cayoshiura** [DallasThomas/SACCHARIS#4]
Hi Dallas,
I tried Saccharis with my seqs using this command and parameters:
> Saccharis.pl -g 'characterized, all' -f GH1 -r raxmlHPC-PTHREADS-AVX -s CC1_11.fasta

but an error occurred during the merge step of my seqs and cazy: 
User has defined a Fasta file, which will be appeneded to the Cazy Extract file
Need to first determine if the User Fasta file has a proper header
grep: CC1_11.fasta: No such file or directory
User File is valid format - proceeding...

Appending CC1_11.fasta to /home/qiime2/Documents/fabi_dna/ok/fasta/GH1/characterized/cazy/GH1_cazy.mod.fasta
Could not open file CC1_11.fasta: No such file or directory at /usr/local/bin/Saccharis.pl line 213.

What happened? How can I fix it?
Thanks

**Comment by DallasThomas** [comment]
The error you are getting comes from Path discrepancy in where it is looking for the files.  In your call to Saccharis - when you give your Sequence files give the full path to your fasta file.  If you give just the name - then the program assumes the file is in the current working directory.  This directory can change during the run of  Saccharis and is the case here. 

Hope this helps.

**Comment by cayoshiura** [comment]
Oops, sorry. I missed this information.

Thank you!!!

**Comment by DallasThomas** [comment]
That is totally fine.  Have a Merry Christmas.
