### ISSUE TITLE
hello. i have some problems

### ISSUE THREAD

**Issue by byeollee** [DallasThomas/SACCHARIS#6]
hello.
i have some problem...
when  i download the dbcan, i can't hmmpress dbcan-fam-HMMs.txt

```
wget http://csbl.bmb.uga.edu/dbCAN/download.php/dbCAN-fam-HMMs.txt
wget http://csbl.bmb.uga.edu/dbCAN/download.php/hmmscan-parser.sh
hmmpress dbcan-fam-HMMs.txt
```
Error: File existence/permissions problem in trying to open HMM file dbcan-fam-HMMs.txt.
HMM file dbcan-fam-HMMs.txt not found (nor an .h3m binary of it)

this results coming out.

please help me..

thank you

**Comment by byeollee** [comment]
i don't understand download step...
i already all software
but Saccharis.pl not working.

thank you :)

**Comment by DallasThomas** [comment]
Hello byeollee,

So for your first issue - your error is telling you that hmmpress is unable to find the file.  In your wget you download 

--> dbCAN-fam-HMMs.txt

Yet when you try hmmpress you try calling

--> dbcan-fam-HMMs.txt

Which is not the same filename for what you downloaded.  Try

--> hmmpress dbCAN-fam-HMMs.txt

Make sure you are in the same directory this file is located.

For your second comment - I am really going to need more information in order to help you out.  You mentioned you already have all of the software.  I am assuming you mean you have installed dbCAN, Muscle, HMMER, ProtTest, FastTree and RAxML.  Can you test each package to make sure they are all working first?  I am then assuming you downloaded (cloned this repository) all of the perl scripts that make up Saccharis.  Were the scripts added to a location in your PATH? The scripts will also need to be made executable, 

for example --> chmod +x Saccharis.pl

If all of this can be confirmed to have been completed can I ask what it says when you try to run Saccharis?

**Comment by byeollee** [comment]
I am follow each install step for package. but i am not sure it is right.
How can i check the test??

Second one is
When i insert code `./Saccharis.pl`,

this results coming out

Usage:
     Saccharis.pl [-Options [--] [Arguments...]]

Arguments:
     --directory   <path>
     --threads     <threads>              
     --group       <group_name>          
     --family      <family_name>
     --RAXML                   : Flag - to choose RAXML over FastTree
     --raxml       <version_raxml>        
     --seqfile     </path/filename>
     --Fragments               : Boolean Flag - if added means keep Fragments
     --help                    : print Options and Arguments instead of fetching data
     --man                     : print complete man page instead of fetching data

Options:
     --directory | -d  <path>

         : You can set a predefined output directory with this flag, though you
           must give it's path.  Default is Current Working Directory (CWD)

     --threads | -t    <threads>
 
         : This is basically straightforward.  Some scripts allow the use of
           multi-core processing.  Set a number in here from 1 to > <max_cores>
           The default is set at 2.

     --group | -g      <group_name>

         : This can be a single group or a list of groups to run.  Lists are comma
           delimited in single quotes. They are case-sensitive - lowercase please...

           -> eg. characterized
           -> eg. 'characterized, all, bacteria'

         : Allowable GroupNames

           -> all, archaea, bacteria, eukaryota, unclassified, characterized,
              subfamilies

     --family | -f     <family_name>
 
         : This is a single family name. 

           -> eg. GH43
       
           NOTE: You can only run a single family per run...

     --raxml | -r      <version_raxml>

         : There are 3 different raxml programs that you can run, which one you 
           choose will be based off of the age and type of your CPU.
 
           -> Older/Slower CPU           -- raxml
           -> Somewhat Older/Faster CPU  -- raxmlHPC-PTHREADS-SSE3 (default)
           -> Newest Procesors           -- raxmlHPC-PTHREADS-AVX

     --seqfile | -s    </path/filename>

         : If you would like to add your own sequences to this run - this is your 
           chance.  Sequences MUST be in FASTA FORMAT - if they are not the script
           will fail.  Make sure to include path with filename.
         : Sequence Header lines must start with a uniqure 9 character string with
           the following format:

           -> >U[0-9]{1,8} - That is a >U followed by 8 digits

            ex. U00000001

     --Fragments | -F

         : This is a boolean value flag that by default is set to TRUE, which means
           fragments are left out by default.  If you would like to include fragment
           sequences from CAZY, include this flag in our call

is it right??

THANK YOU.

**Comment by DallasThomas** [comment]
To test the different packages - each of the programs documentation provides a way to check that their software has been installed properly.

As for Saccharis.pl this is the output you would expect if called the way you called it.

**Comment by byeollee** [comment]
Thank You so much,

 I check each package can run. All run well👌

Could you give the some example?? I am not sure I run well using Saccharis.pl

Oh also, I am still can’t hmmpress dbCAN-fam-HMMs.txt. so I download hmmpress results file. is it fine??

Thank you 😄

**Comment by byeollee** [comment]
Hello there.

when i run the `perl cazy_extract.pl --family CE4 --group all --Fragment false`

this results coming out

Attempt to bless into a reference at /usr/local/share/perl/5.26.1/HTML/TagParser.pm line 236.

what can i do?? please help me. i don't know.... what is wrong

thank you

**Comment by DallasThomas** [comment]
Under the instructions in the Readme there is a heading that deals with this issue.  There is a problem with one of the lines in the perl library TagParser.pm that you need to change.

You will need to use an editor and open the file TagParser.pm at the location given in your error then goto line 236 and change the line to the following:


bless $self, ref($package) || $package;
