### ISSUE TITLE
problem with cazy_extract.pl

### ISSUE THREAD

**Issue by camillaln** [DallasThomas/SACCHARIS#9]
Hi,

I am having some issues with running  Saccharis.pl getting errors saying cazy_extract.pl is not found.

When I run Saccharis.pl I get this error:

Program Command : Saccharis.pl --group characterized --seqfile /groups/edwards/camilla/Bathyarchaeota/Cazymes/GH77/BathyGH77.fasta --family GH77 

==============================================================================

Begin pipeline analysis for group: characterized of family GH77
Cazy Extract is proceeding for characterized of family GH77
Running Cazy Extract Script
Commands To Run - 
        cazy_extract.pl -f GH77 -g characterized; 

Threading: cazy_extract.pl -f GH77 -g characterized; 
sh: cazy_extract.pl: command not found
************************** Threading Ended
Threading: 
************************** Threading Ended
Cazy Sequences have been extracted

Completed Cazy Extract

==============================================================================

Cannnot open /nfs/homes/nesbocam/SACCHARIS/GH77/characterized/cazy/sequence.count for reading: No such file or directory at ./Saccharis.pl line 156.

When I run 
cazy_extract.pl -f GH77 -g characterized

I do get files  called GH77_cazy.fasta and sequence.count , so the sequences are extracted from Genbank.
Thanks a million for any help with this - I would very much like to use your very useful scripts!!]
Camilla

**Comment by DallasThomas** [comment]
Hello Camilla, 

Would you mind if I ask a few questions to better be able to help here.

How was Saccharis installed?  For example when you run Saccharis is it in your Path and can be run just as:

Saccharis.pl

or do you run it as

./<path>/Saccharis.pl

When Saccharis calls cazy_extract.pl the first thing it does is create the cazy subdirectory and change to it, before it runs cazy_extract.pl

I am just trying to confirm that cazy_extract.pl can be found from

/nfs/homes/nesbocam/SACCHARIS/GH77/characterized/cazy

When you ran cazy_extract.pl by itself, did you by chance run it in the path above?

Any additional information you might provide would be very much appreciated.

**Comment by camillaln** [comment]
Hi,

Thanks for your quick reply!
I put Saccharis.pl in my path - and now it makes folders and runs all the way to hmmscan-parser.sh. I noticed that my dbCAN folder with the hmm does not have all.hmm.ps.len in it and I cannot find it on the dbCAN website - could that be the issue???

In the SACCHARIS/GH77/dbcan folder only these files have content:
GH77.hmm.out
GH77.hmm.out.dm

This is my error - and I also attached the output written to my 'out' file.

(base) nesbocam@silicon:~/SACCHARIS$ Saccharis.pl --group characterized --seqfile /groups/edwards/camilla/Bathyarchaeota/Cazymes/GH77/BathyGH77.fasta --family GH77 > out
from: too many arguments
import.im6: unable to open X server `' @ error/import.c/ImportImageCommand/368.
hmmscan-parser.sh: line 21: =: command not found
hmmscan-parser.sh: line 22: coverage: command not found
hmmscan-parser.sh: line 24: syntax error near unexpected token `sys.argv'
hmmscan-parser.sh: line 24: `if len(sys.argv) > 1:'

MUSCLE v3.8.31 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.


*** ERROR ***  No sequences in input file
Can't open GH77.muscle_aln.phyi:No such file or directory
awk: fatal: cannot open file `GH77.muscle_aln_mod.phyi' for reading: No such file or directory
cp: cannot stat '/usr/local/prottest3/prottest.properties': No such file or directory
Error: Unable to access jarfile /usr/local/prottest3/prottest3.jar
Cannot open /nfs/homes/nesbocam/SACCHARIS/GH77/characterized/prottest/GH77.prottest.out No such file or directory

I also had to do some modifications to point your script to the directories on the server I use, so I have attached Saccharis.pl script I use as well incase I made a mistake.

[out.txt](https://github.com/DallasThomas/SACCHARIS/files/7721781/out.txt)
[Saccharis.pl.txt](https://github.com/DallasThomas/SACCHARIS/files/7721816/Saccharis.pl.txt)

**Comment by DallasThomas** [comment]
Thanks for the update.  There have been some updates to dbcan among other things.  There currently are plans for an updated Saccharis v2 that hopefully will be coming soon.

For now I have commented out the section dealing with all.hmm.ps.len as this was removed in one of the more recent dbcan updates.

If you replace your Saccharis.pl with the current one here - give this a shot.  Changes to code were made on lines 506-509

Hope this helps.

Dallas

**Comment by camillaln** [comment]
Hi,
I tried the new Saccharis.pl and it worked after I did a couple of edits.
I can only run  hmmscan-parser.sh as python hmmscan-parser.sh - sh hmmscan-parser.sh did nothing, so I changed sh hmmscan-parser.sh to python hmmscan-parser.sh and that worked!!
I also had to change the location of the prottest3 jar - in the current version it was in prottest3/dist/prottest-3.4.2.jar

Thank you so much for all your help!

**Comment by DallasThomas** [comment]
Hello,
I am glad it is working for you.  I will jot this down and make a note of it so others will not run into the same issue, in the interim before the next version is available.
Thank-you for reaching out, this is always helpful.

Dallas
